/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:496b3d61-c256-44c9-8b08-3e46b68cc0ce",
    "aws_cognito_region": "eu-west-1",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_test",
            "alias": "$LATEST",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
